### ISSUE TITLE
Understand impact of (many) histogram axes

### ISSUE THREAD

**Issue by riga** [uhh-cms/analysis_playground#12]
When using the n-D histograms in the future, we need to understand how we setup axes.

The default will for sure contain sth like (process_id_or_name, shift_id_or_name, category_id_or_name, ..., variable), but maybe we can also add more than just one variable to be able to make every possible 2D plot, or apply some late (discretized since already binned) cuts. Constraints will be memory, and runtime.

**Comment by mafrahm** [comment]
I have implemented a task that creates N-dimensional histograms.
Test case:
1 category axis, 10 bins + N variable axes, 40 bins each

output size:
3 axes: 13 MB
4 axes: 523 MB
5 axes: >4GB (Error due to pickle file size)
6 axes: MemoryError: std::bad_alloc

**Comment by riga** [comment]
Yeah, this seems rather unfeasible (as kinda expected) so I assume we will rather opt for 2D hists of interesting combinations.

@mafrahm Feel free to close

**Comment by mafrahm** [comment]
It should still be possible to create higher-dimension histograms in special cases (e.g. saving the discriminating variable in addition to 2-3 interesting variables which one might want to test different cuts on).
However, the upper limit of bins in total should be somewhere around 10^8 (~2GB file size).
