### ISSUE TITLE
`sort_ak_fields` function not working with nested array structure

### ISSUE THREAD

**Issue by pkausw** [uhh-cms/analysis_playground#42]
In the scope of PR #37 , I noticed that the function `sort_ak_fields` raises a rather cryptic error. Here is the backtrace:

```bash
/nfs/dust/cms/user/pkeicher/uhh/u4h/analysis_playground/ap/selection/__init__.py in <module>
----> 1 sort_ak_fields(ak_array)

/nfs/dust/cms/user/pkeicher/uhh/u4h/analysis_playground/ap/columnar_util.py in sort_ak_fields(ak_array, sort_fn)
    366     for field in nested_fields:
--> 367         ak_array[field] = sort_ak_fields(ak_array[field], sort_fn=sort_fn)
    368
    369     return ak_array

/nfs/dust/cms/user/pkeicher/uhh/u4h/analysis_playground/data/software/venvs/venv_columnar_dev/lib64/python3.6/site-packages/awkward/highlevel.py in __setitem__(self, where, what)
   1060                     + ak._util.exception_suffix(__file__)
   1061                 )
-> 1062             array = ak.operations.structure.with_field(self.layout, what, where)
   1063             self._layout = array.layout
   1064             self._caches = ak._util.find_caches(self.layout)

/nfs/dust/cms/user/pkeicher/uhh/u4h/analysis_playground/data/software/venvs/venv_columnar_dev/lib64/python3.6/site-packages/awkward/operations/structure.py in with_field(base, what, where, highlevel, behavior)
    997         if len(keys) == 0:
    998             # the only key was removed, so just create new Record
--> 999             out = (ak.layout.RecordArray([what], [where], parameters=base.parameters),)
   1000
   1001         else:

ValueError: content argument must be a Content subtype

(https://github.com/scikit-hep/awkward-1.0/blob/1.8.0/src/python/content.cpp#L342)
```

After some research, I found a couple of threads (e.g. [this](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html#ak-array-setitem) ) that all point to the fact that awkward arrays are immutable - you can add _new_ fields, but you cannot replace existing once.
In  PR #37 , I create a new array and basically copy the sorted fields into the new array. 
This of course is neither elegant nor efficient, both CPU- and memory-wise.

Therefore, I created this issue so we can find a better way.
Perhaps I missed something and I would be glad for more opinions :) For instance, given that the arrays are immutable, I'm not sure how this part of the code ever worked with nested arrays obtained from e.g. a SelectionResult object.
Is there anyone who can comment on this?

**Comment by pkausw** [comment]
I also have an idea how to improve this, but I don't know how feasible it is yet. 

In my opinion, the most efficient way to sort the fields in the array would be to work with the `layout` of the array, which has an xml format. Here is an example:

```xml
<IrregularlyPartitionedArray>
    <partition start="0" stop="50000">
        <RecordArray length="50000">
            <field index="0" key="objects">
                <RecordArray length="50000">
                    <field index="0" key="Jet">
                        <ListOffsetArray64>
                            <offsets><Index64 i="[0 7 10 20 23 24 29 34 41 45 ... 274057 274068 274073 274083 274089 274097 274105 274113 274120 274124]" offset="0" length="50001" at="0x000002a2a700"/></offsets>
                            <content><IndexedOptionArray64>
                                <index><Index64 i="[0 1 2 3 4 5 6 7 8 9 ... -1 -1 -1 -1 -1 -1 188203 188204 188205 188206]" offset="0" length="274124" at="0x000003521c80"/></index>
                                <content><NumpyArray format="l" shape="188207" data="0 1 2 3 4 ... 7 0 1 2 3" at="0x000003abc6f0"/></content>
                            </IndexedOptionArray64></content>
                        </ListOffsetArray64>
                    </field>
                </RecordArray>
            </field>
        </RecordArray>
    </partition>
</IrregularlyPartitionedArray>
```

All we would need to do is change the indices in this structure. Since the `layout` contains the information about where the actual data is stored, no copy operation should be necessary. I spend some time playing around with this, but so far I couldn't figure out 
- how to get a mutable `layout` and do the sorting
- create an array directly from the layout. I thought that the [ak.ArrayBuilder](https://awkward-array.readthedocs.io/en/latest/_auto/ak.ArrayBuilder.html#ak-arraybuilder) class is a promising starting point for this, but so far I couldn't pass a layout to this class. The only thing I was able to do was create things on an event-by-event basis, which surely we don't want to do

**Comment by riga** [comment]
Is that still a thing given that the helper function was updated in the meantime?

**Comment by pkausw** [comment]
I checked, this is not an issue anymore :+1:
