### ISSUE TITLE
Implement configs for recorded data

### ISSUE THREAD

**Issue by dsavoiu** [uhh-cms/analysis_playground#50]
This is probably very far down the priority list, since we will be testing with MC first anyway, but it would be good to figure out how the configs for the real/recorded data should look like and what additional auxiliary config entries would be needed. At the very least one would need to organize the datasets by era and configure era-dependent corrections/scale factors/etc.

**Comment by riga** [comment]
Good point. Maybe we should add one era of `SingleMuon` to the campaign and config?
